---
- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox_exporter
  service:
    name: blackbox_exporter
    state: reloaded

- name: stop blackbox_exporter
  service:
    name: blackbox_exporter
    state: stopped
