---
- name: Install systemd configuration file
  template:
    src: blackbox_exporter_systemd.j2
    dest: /etc/systemd/system/blackbox_exporter.service

- name: Create configuration file
  template:
    src: blackbox_exporter_config.yml.j2
    dest: "{{ blackbox_exporter_dir }}/blackbox.yml"
